// NKB Manufacturing Enterprise Canteen Employee Database Cache
// Auto-synced with https://canteen.nkbmanufacturing.com/api/integration/employees
window.NKB_CANTEEN_EMPLOYEES = [
  {"id":14,"employee_id":"NKB052026-0003","name":"Alonzo, Merry Jean I.","department":"Production","position":"Staff","status":"Active"},
  {"id":52,"employee_id":"PRJ2026-0001","name":"Amolo, Wenjielyn","department":"Production","position":"Staff","status":"Active"},
  {"id":15,"employee_id":"NKB052026-0004","name":"Atayde, Emmie M.","department":"Production","position":"Staff","status":"Active"},
  {"id":16,"employee_id":"NKB052026-0005","name":"Atayde, Marvin G.","department":"Security","position":"Security Officer","status":"Active"},
  {"id":17,"employee_id":"NKB052026-0006","name":"Bautista, Allen L.","department":"Production","position":"Staff","status":"Active"},
  {"id":12,"employee_id":"NKB052026-0001","name":"Bella, Katherine A.","department":"CEO","position":"Executive","status":"Active"},
  {"id":13,"employee_id":"NKB052026-0002","name":"Bella, Norvin L.","department":"COO","position":"Executive","status":"Active"},
  {"id":108,"employee_id":"PRJ2026-0039","name":"BERTUDAZO, CHARLOTTE R.","department":"Maintenance","position":"Technician","status":"Active"},
  {"id":83,"employee_id":"PRJ2026-0032","name":"Bobadilla, Michael","department":"Production","position":"Staff","status":"Active"},
  {"id":53,"employee_id":"PRJ2026-0002","name":"Bombita, Rafael Rannie","department":"Production","position":"Staff","status":"Active"},
  {"id":18,"employee_id":"NKB052026-0007","name":"Bombita, Raniella Camille","department":"Production","position":"Quality Control","status":"Active"},
  {"id":19,"employee_id":"NKB052026-0008","name":"Boston, Kem Mariel","department":"Regulatory","position":"Specialist","status":"Active"},
  {"id":94,"employee_id":"VYU2026-0001","name":"Boston, Monet","department":"Vyuceutical","position":"Specialist","status":"Active"},
  {"id":54,"employee_id":"PRJ2026-0003","name":"Camaña, Rose Pauline","department":"Production","position":"Staff","status":"Active"},
  {"id":55,"employee_id":"PRJ2026-0004","name":"Carel, Carlo Jay","department":"Production","position":"Staff","status":"Active"},
  {"id":20,"employee_id":"NKB052026-0009","name":"Catalan, Jhon Jhon B.","department":"Production","position":"Staff","status":"Active"},
  {"id":56,"employee_id":"PRJ2026-0005","name":"Cate, Dominick","department":"Production","position":"Staff","status":"Active"},
  {"id":21,"employee_id":"NKB052026-0010","name":"Catindig, Renar A.","department":"Compounding","position":"Specialist","status":"Active"},
  {"id":57,"employee_id":"PRJ2026-0006","name":"Cedillo, Jamrex","department":"Production","position":"Staff","status":"Active"},
  {"id":58,"employee_id":"PRJ2026-0007","name":"Corral, Rex C.","department":"Production","position":"Staff","status":"Active"},
  {"id":22,"employee_id":"NKB052026-0011","name":"Corral, Rodolfo C.","department":"Maintenance","position":"Technician","status":"Active"},
  {"id":23,"employee_id":"NKB052026-0012","name":"Cuya, Roberto","department":"Construction","position":"Maintenance","status":"Active"},
  {"id":59,"employee_id":"PRJ2026-0008","name":"Dalanon, Mark B.","department":"Production","position":"Staff","status":"Active"},
  {"id":60,"employee_id":"PRJ2026-0009","name":"Dalanon, Mars B.","department":"Production","position":"Staff","status":"Active"},
  {"id":24,"employee_id":"NKB052026-0013","name":"De Jesus, Khayle Nicole G.","department":"Production","position":"Staff","status":"Active"},
  {"id":61,"employee_id":"PRJ2026-0010","name":"Del Rosario, Mary Ann","department":"Maintenance","position":"Staff","status":"Active"},
  {"id":62,"employee_id":"PRJ2026-0011","name":"Del Socorro, Mary Grace","department":"Production","position":"Staff","status":"Active"},
  {"id":63,"employee_id":"PRJ2026-0012","name":"Dela Cruz, Vincent Lloyd","department":"Inventory / Warehouse","position":"Warehouse Staff","status":"Active"},
  {"id":25,"employee_id":"NKB052026-0014","name":"Delos Santos, Earl John","department":"IT Administration","position":"Systems Administrator","status":"Active"},
  {"id":1,"employee_id":"EMP-000001","name":"Earl John Delos Santos","department":"IT Administration","position":"Systems Administrator","status":"Active"},
  {"id":64,"employee_id":"PRJ2026-0013","name":"Fabio, Marilou","department":"QC","position":"Quality Control","status":"Active"},
  {"id":26,"employee_id":"NKB052026-0015","name":"Garcia, Jayvee G.","department":"Production","position":"Staff","status":"Active"},
  {"id":84,"employee_id":"NKB052026-0041","name":"Garcia, Jonnel","department":"Driver","position":"Driver","status":"Active"},
  {"id":65,"employee_id":"PRJ2026-0014","name":"Gerero, Raquel","department":"Production","position":"Staff","status":"Active"},
  {"id":88,"employee_id":"PRJ2026-0036","name":"Guillermo, Isagani","department":"Construction","position":"Mason","status":"Active"},
  {"id":27,"employee_id":"NKB052026-0016","name":"Guillermo, Jaime","department":"Construction","position":"Foreman","status":"Active"},
  {"id":28,"employee_id":"NKB052026-0017","name":"Gutierrez, Heramae","department":"Purchasing","position":"Purchasing Officer","status":"Active"},
  {"id":29,"employee_id":"NKB052026-0018","name":"Ilano, Maximo Jr. R.","department":"Marketing","position":"Marketing Staff","status":"Active"},
  {"id":122,"employee_id":"NKB202607260122","name":"Jamrex Cedillo","department":"Production","position":"Staff","status":"Active"},
  {"id":111,"employee_id":"NKB202607200111","name":"Jhon Jhon Catalan","department":"Printing","position":"Operator","status":"Active"},
  {"id":30,"employee_id":"NKB052026-0019","name":"Jurado, Genevieve Anne A.","department":"HR","position":"HR Specialist","status":"Active"},
  {"id":66,"employee_id":"PRJ2026-0015","name":"Laungayan, Jason","department":"Security","position":"Security Officer","status":"Active"},
  {"id":67,"employee_id":"PRJ2026-0016","name":"Laungayan, Marivic","department":"Production","position":"Staff","status":"Active"},
  {"id":31,"employee_id":"NKB052026-0020","name":"Luy, Rodello","department":"Inventory / Warehouse","position":"Inventory Head","status":"Active"},
  {"id":32,"employee_id":"NKB052026-0021","name":"Macafe, Angelita","department":"R&D","position":"R&D Specialist","status":"Active"},
  {"id":68,"employee_id":"PRJ2026-0017","name":"Macol, Vincent","department":"Production","position":"Driver","status":"Active"},
  {"id":51,"employee_id":"NKB052026-0040","name":"Madelo, Edwin","department":"Accounting","position":"Accounting Officer","status":"Active"},
  {"id":85,"employee_id":"PRJ2026-0033","name":"Magan, Edmar John","department":"Construction","position":"Staff","status":"Active"},
  {"id":69,"employee_id":"PRJ2026-0018","name":"Maglangit, Melina","department":"Maintenance","position":"Staff","status":"Active"},
  {"id":33,"employee_id":"NKB052026-0022","name":"Mananquil, Mark Gleen","department":"Production","position":"Staff","status":"Active"},
  {"id":86,"employee_id":"PRJ2026-0034","name":"Mananquil, Elmedio Jr","department":"Construction","position":"Staff","status":"Active"},
  {"id":34,"employee_id":"NKB052026-0023","name":"Mangulabnan, Ana Marie V.","department":"Housekeeping","position":"Staff","status":"Active"},
  {"id":35,"employee_id":"NKB052026-0024","name":"Manuel, Nannette","department":"Coop","position":"Staff","status":"Active"},
  {"id":97,"employee_id":"VYU2026-0003","name":"MARBIBI, MELANIE D","department":"Vyuceutical","position":"Specialist","status":"Active"},
  {"id":121,"employee_id":"NKB202607260121","name":"Marife Mendoza","department":"Production","position":"Staff","status":"Active"},
  {"id":36,"employee_id":"NKB052026-0025","name":"Martin, Michelle","department":"Business Development","position":"Specialist","status":"Active"},
  {"id":70,"employee_id":"PRJ2026-0019","name":"Mejorada, Roselyn","department":"Production","position":"Operator","status":"Active"},
  {"id":71,"employee_id":"PRJ2026-0020","name":"Mendoza, Marife","department":"Production","position":"Staff","status":"Active"},
  {"id":124,"employee_id":"NKB072026-0042","name":"Mendoza, Porchia Soffia Louisse","department":"Marketing","position":"Marketing Specialist","status":"Active"},
  {"id":37,"employee_id":"NKB052026-0026","name":"Mendoza, Sonny","department":"Production","position":"Cutting Lead","status":"Active"},
  {"id":38,"employee_id":"NKB052026-0027","name":"Mercado, Jaycel D.","department":"Inventory / Warehouse","position":"Warehouse Team Lead","status":"Active"},
  {"id":72,"employee_id":"PRJ2026-0021","name":"Mirambil, Darius","department":"Production","position":"Staff","status":"Active"},
  {"id":73,"employee_id":"PRJ2026-0022","name":"Mirambil, Leo","department":"Silkscreen","position":"Production Operator","status":"Active"},
  {"id":74,"employee_id":"PRJ2026-0023","name":"Mirambil, Michael","department":"Production","position":"Staff","status":"Active"},
  {"id":95,"employee_id":"PRJ2026-0038","name":"Mirambil, Monica","department":"Production","position":"Staff","status":"Active"},
  {"id":39,"employee_id":"NKB052026-0028","name":"Mirambil, Ricky O.","department":"Security","position":"Security Officer","status":"Active"},
  {"id":40,"employee_id":"NKB052026-0029","name":"Mirambil, Rommel M.","department":"Production","position":"Staff","status":"Active"},
  {"id":41,"employee_id":"NKB052026-0030","name":"Mirambil, Rosanna O.","department":"Housekeeping","position":"Staff","status":"Active"},
  {"id":42,"employee_id":"NKB052026-0031","name":"Molina, Rose Ann","department":"Vyuceutical","position":"Live Seller","status":"Active"},
  {"id":43,"employee_id":"NKB052026-0032","name":"Nabong, Dorina","department":"Accounting","position":"Accounting Staff","status":"Active"},
  {"id":107,"employee_id":"NKB072026-0041","name":"NGOHO, JILLIANA MARIE B.","department":"General Operations","position":"Staff","status":"Active"},
  {"id":44,"employee_id":"NKB052026-0033","name":"Nobleza, Glenn L.","department":"Maintenance","position":"Staff","status":"Active"},
  {"id":45,"employee_id":"NKB052026-0034","name":"Obamos, Rodalia G.","department":"Production","position":"Staff","status":"Active"},
  {"id":75,"employee_id":"PRJ2026-0024","name":"Omandac, Jayson","department":"Production","position":"Staff","status":"Active"},
  {"id":76,"employee_id":"PRJ2026-0025","name":"Orongan, Jocelyn","department":"Production","position":"Staff","status":"Active"},
  {"id":77,"employee_id":"PRJ2026-0026","name":"Padilla, Creiver John","department":"Production","position":"Staff","status":"Active"},
  {"id":46,"employee_id":"NKB052026-0035","name":"Panis, Priman","department":"Construction","position":"Electrical","status":"Active"},
  {"id":126,"employee_id":"NKB082026-0044","name":"Pellazar, Mavick Pauleen Roma","department":"Marketing","position":"Marketing Staff","status":"Active"},
  {"id":78,"employee_id":"PRJ2026-0027","name":"Presentacion, Jaysie G.","department":"Production","position":"Staff","status":"Active"},
  {"id":47,"employee_id":"NKB052026-0036","name":"Prudencio, Ronaldo","department":"Production","position":"Staff","status":"Active"},
  {"id":48,"employee_id":"NKB052026-0037","name":"Razo, Dennis R.","department":"Accounting","position":"Accounting Officer","status":"Active"},
  {"id":79,"employee_id":"PRJ2026-0028","name":"Regala, Ronald","department":"Production","position":"Staff","status":"Active"},
  {"id":96,"employee_id":"VYU2026-0002","name":"ROCERO, JUSTINE","department":"Vyuceutical","position":"Staff","status":"Active"},
  {"id":98,"employee_id":"PRJ2026-0037","name":"SALCEDO, ANA O.","department":"Production","position":"Staff","status":"Active"},
  {"id":49,"employee_id":"NKB052026-0038","name":"Santos, Sharmaine E.","department":"Accounting","position":"Accounting Staff","status":"Active"},
  {"id":80,"employee_id":"PRJ2026-0029","name":"Soriano, Joel","department":"Production","position":"Staff","status":"Active"},
  {"id":81,"employee_id":"PRJ2026-0030","name":"Soriano, Joylen","department":"Production","position":"Staff","status":"Active"},
  {"id":125,"employee_id":"NKB072026-0043","name":"Taguan, Angelica T.","department":"Marketing","position":"Staff","status":"Active"},
  {"id":87,"employee_id":"PRJ2026-0035","name":"Taruc, Michael","department":"Construction","position":"Staff","status":"Active"},
  {"id":50,"employee_id":"NKB052026-0039","name":"Valiao, Reynan P.","department":"Marketing","position":"Marketing Staff","status":"Active"},
  {"id":82,"employee_id":"PRJ2026-0031","name":"Valle, Leonard","department":"Production","position":"Staff","status":"Active"}
];
